import type { KnipConfig } from "knip";

const config = {
  entry: [
    "astro.config.ts",
    "eslint/**/*.ts",
    "eslint.config.ts",
    "examples/platform-entrypoint-consumer/**/*.ts",
    "lighthouserc.json",
    "playwright.config.ts",
    "scripts/**/*.ts",
    "src/content.config.ts",
    "src/lib/deployment/deployment-adapters.ts",
    "src/lib/extensions/extensions.ts",
    "src/lib/import-export/migration-fixtures.ts",
    "src/lib/localization/localization-fixtures.ts",
    "src/lib/release/release-governance.ts",
    "src/lib/release/static-output-security.ts",
    "src/lib/release/supply-chain-policy.ts",
    "src/lib/release/third-party-origins.ts",
    "src/lib/starters/starter-templates.ts",
    "src/pages/**/*.{astro,ts,tsx}",
    "src/platform/**/*.ts",
    "src/scripts/**/*.ts",
    "tests/**/*.ts",
  ],
  ignore: [
    ".astro/**",
    ".lighthouseci/**",
    ".unlighthouse/**",
    ".wrangler/**",
    "coverage/**",
    "dist/**",
    "dist-catalog/**",
    "playwright-report/**",
    "public/**",
    "test-results/**",
  ],
  ignoreBinaries: ["gitleaks"],
  ignoreDependencies: [
    "@typescript-eslint/parser",
    "@tailwindcss/typography",
    "html-validate",
    "markdownlint-cli2",
    "pagefind",
    "sort-package-json",
    "tailwindcss",
    "tw-animate-css",
  ],
  project: [
    "astro.config.ts",
    "eslint/**/*.ts",
    "eslint.config.ts",
    "examples/platform-entrypoint-consumer/**/*.ts",
    "playwright.config.ts",
    "scripts/**/*.ts",
    "src/**/*.{astro,ts,tsx}",
    "tests/**/*.ts",
  ],
} satisfies KnipConfig;

export default config;
