import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { ImageMetadata } from "astro";
import { toJSONSchema, z } from "astro/zod";
import {
  format as formatWithPrettier,
  resolveConfig as resolvePrettierConfig,
} from "prettier";

import {
  authorDiagnosticCategories,
  authorDiagnosticFixabilities,
  authorDiagnosticRepairOwners,
  authorDiagnosticSources,
} from "../../src/lib/author-diagnostics";
import {
  announcementSchema,
  articleSchema,
  authorSchema,
  categorySchema,
  editorialCollectionSchema,
  pageSchema,
} from "../../src/lib/content-schemas";
import {
  articleMdxPdfCompatibilityPolicies,
  type MediaRole,
  mediaRoles,
  type MediaSurface,
  mediaSurfaces,
  socialPreviewMediaPolicy,
} from "../../src/lib/media-policy";
import { routeRegistryEntries } from "../../src/lib/route-registry";
import { semanticProfileKinds } from "../../src/lib/semantic-profile-kinds";
import { siteConfig } from "../../src/lib/site-config";
import {
  defaultFeatureConfig,
  defaultPublishableVisibilityConfig,
  siteFeatureKeys,
} from "../../src/lib/site-config-defaults";
import { projectRelativePath, siteInstance } from "../../src/lib/site-instance";
import { sourceArtifactManifest } from "../../src/lib/source-artifacts";
import {
  qaCommandGroups,
  qaDomainCoverageRegistry,
} from "../quality/qa-command-registry";
import { siteConfigJsonSchema } from "../site/generate-site-config-schema";

const defaultOutputPath = path.join(
  process.cwd(),
  "docs/generated/platform-reference.md",
);

interface GeneratePlatformReferencesCliIo {
  stderr: Pick<typeof process.stderr, "write">;
  stdout: Pick<typeof process.stdout, "write">;
}

interface JsonSchemaField {
  defaultValue: string;
  path: string;
  required: string;
  type: string;
}

type JsonRecord = Record<string, unknown>;

/**
 * Builds the generated platform reference Markdown from current source
 * contracts.
 *
 * @returns Deterministic generated Markdown.
 */
export function generatedPlatformReferenceMarkdown(): string {
  return [
    "# Generated Platform Reference",
    "",
    "> Generated by `bun run docs:references`. Do not edit by hand.",
    "",
    "This file is generated from platform schemas and registries so docs can",
    "reference current contracts without copying implementation facts by hand.",
    "",
    ...siteConfigReferenceSection(),
    ...frontmatterReferenceSection(),
    ...routeReferenceSection(),
    ...featureReferenceSection(),
    ...visibilityReferenceSection(),
    ...metadataReferenceSection(),
    ...mediaReferenceSection(),
    ...authorDiagnosticReferenceSection(),
    ...sourceArtifactReferenceSection(),
    ...qaCommandReferenceSection(),
    "",
  ].join("\n");
}

/**
 * Formats generated platform reference Markdown with the repository Markdown
 * formatter so generated docs and `fix:markdown` share one canonical shape.
 *
 * @param markdown Raw generated Markdown.
 * @param outputPath Path used for parser inference and diagnostics.
 * @returns Prettier-canonical Markdown.
 */
async function formatGeneratedPlatformReferenceMarkdown(
  markdown: string,
  outputPath = defaultOutputPath,
): Promise<string> {
  const options = await resolvePrettierConfig(defaultOutputPath);

  return formatWithPrettier(markdown, {
    ...options,
    filepath: outputPath,
  });
}

/**
 * Runs the platform reference generator CLI.
 *
 * @param args CLI arguments.
 * @param io Output writers.
 * @returns Process exit code.
 */
export async function runGeneratePlatformReferencesCli(
  args = Bun.argv.slice(2),
  io: GeneratePlatformReferencesCliIo = {
    stderr: process.stderr,
    stdout: process.stdout,
  },
): Promise<number> {
  if (args.includes("--help")) {
    io.stdout.write(usage());

    return 0;
  }

  const outputPath = outputPathFromArgs(args);
  const quiet = args.includes("--quiet");
  const check = args.includes("--check");
  const text = await formatGeneratedPlatformReferenceMarkdown(
    generatedPlatformReferenceMarkdown(),
    outputPath,
  );

  if (check) {
    const existingText = readFileSync(outputPath, "utf8");

    if (existingText === text) {
      if (!quiet) {
        io.stdout.write(
          `Generated platform reference is current at ${projectRelativePath(
            outputPath,
          )}.\n`,
        );
      }

      return 0;
    }

    io.stderr.write(
      `Generated platform reference is stale at ${projectRelativePath(
        outputPath,
      )}. Run bun run docs:references.\n`,
    );

    return 1;
  }

  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, text);

  if (!quiet) {
    io.stdout.write(
      `Wrote generated platform reference to ${projectRelativePath(
        outputPath,
      )}.\n`,
    );
  }

  return 0;
}

function siteConfigReferenceSection(): string[] {
  return [
    "## Site Config Fields",
    "",
    "Source: `src/lib/site-config.ts` and `site/config/site.schema.json`.",
    "",
    table(
      ["Field", "Type", "Required", "Default"],
      schemaFields(siteConfigJsonSchema()).map((field) => [
        field.path,
        field.type,
        field.required,
        field.defaultValue,
      ]),
    ),
    "",
  ];
}

function frontmatterReferenceSection(): string[] {
  const schemas = [
    {
      label: "Article frontmatter",
      schema: toJSONSchema(
        articleSchema(
          imageSchemaContext(),
          siteConfig.contentDefaults.articles,
          siteConfig.metadata,
        ),
        { io: "input", unrepresentable: "any" },
      ),
      source: "articleSchema()",
    },
    {
      label: "Announcement frontmatter",
      schema: toJSONSchema(
        announcementSchema(
          imageSchemaContext(),
          siteConfig.contentDefaults.announcements,
          siteConfig.metadata,
        ),
        { io: "input", unrepresentable: "any" },
      ),
      source: "announcementSchema()",
    },
    {
      label: "Page frontmatter",
      schema: toJSONSchema(pageSchema(imageSchemaContext()), {
        io: "input",
        unrepresentable: "any",
      }),
      source: "pageSchema()",
    },
    {
      label: "Category metadata",
      schema: toJSONSchema(categorySchema(), {
        io: "input",
        unrepresentable: "any",
      }),
      source: "categorySchema()",
    },
    {
      label: "Author metadata",
      schema: toJSONSchema(authorSchema(), {
        io: "input",
        unrepresentable: "any",
      }),
      source: "authorSchema()",
    },
    {
      label: "Collection frontmatter",
      schema: toJSONSchema(editorialCollectionSchema(), {
        io: "input",
        unrepresentable: "any",
      }),
      source: "editorialCollectionSchema()",
    },
  ];

  return [
    "## Content Frontmatter Fields",
    "",
    "Source: `src/lib/content-schemas.ts`.",
    "",
    ...schemas.flatMap(({ label, schema, source }) => [
      `### ${label}`,
      "",
      `Source function: \`${source}\`.`,
      "",
      table(
        ["Field", "Type", "Required", "Default"],
        schemaFields(schema).map((field) => [
          field.path,
          field.type,
          field.required,
          field.defaultValue,
        ]),
      ),
      "",
    ]),
  ];
}

function routeReferenceSection(): string[] {
  return [
    "## Routes, Entities, Features, And Output",
    "",
    "Source: `src/lib/route-registry.ts` and active `site/config/site.json`.",
    "",
    table(
      [
        "Route key",
        "Route",
        "Entity",
        "Feature",
        "Enabled",
        "Output",
        "Surfaces",
      ],
      routeRegistryEntries(siteConfig).map((entry) => [
        entry.routeKey,
        entry.route,
        entry.entity,
        entry.feature ?? "",
        String(entry.enabled),
        entry.outputPath,
        entry.surfaces.join(", "),
      ]),
    ),
    "",
  ];
}

function featureReferenceSection(): string[] {
  return [
    "## Feature Flags",
    "",
    "Source: `src/lib/site-config-defaults.ts` and active `site/config/site.json`.",
    "",
    table(
      ["Feature", "Default", "Current"],
      siteFeatureKeys.map((feature) => [
        feature,
        String(defaultFeatureValue(feature)),
        String(currentFeatureValue(feature)),
      ]),
    ),
    "",
  ];
}

function defaultFeatureValue(
  feature: (typeof siteFeatureKeys)[number],
): boolean {
  switch (feature) {
    case "announcements":
      return defaultFeatureConfig.announcements;

    case "authors":
      return defaultFeatureConfig.authors;

    case "bibliography":
      return defaultFeatureConfig.bibliography;

    case "categories":
      return defaultFeatureConfig.categories;

    case "collections":
      return defaultFeatureConfig.collections;

    case "feed":
      return defaultFeatureConfig.feed;

    case "pdf":
      return defaultFeatureConfig.pdf;

    case "search":
      return defaultFeatureConfig.search;

    case "support":
      return defaultFeatureConfig.support;

    case "tags":
      return defaultFeatureConfig.tags;

    case "themeToggle":
      return defaultFeatureConfig.themeToggle;
  }
}

function currentFeatureValue(
  feature: (typeof siteFeatureKeys)[number],
): boolean {
  switch (feature) {
    case "announcements":
      return siteConfig.features.announcements;

    case "authors":
      return siteConfig.features.authors;

    case "bibliography":
      return siteConfig.features.bibliography;

    case "categories":
      return siteConfig.features.categories;

    case "collections":
      return siteConfig.features.collections;

    case "feed":
      return siteConfig.features.feed;

    case "pdf":
      return siteConfig.features.pdf;

    case "search":
      return siteConfig.features.search;

    case "support":
      return siteConfig.features.support;

    case "tags":
      return siteConfig.features.tags;

    case "themeToggle":
      return siteConfig.features.themeToggle;
  }
}

function visibilityReferenceSection(): string[] {
  return [
    "## Publishable Visibility Surfaces",
    "",
    "Source: `src/lib/site-config-defaults.ts`.",
    "",
    table(
      ["Surface", "Default"],
      Object.entries(defaultPublishableVisibilityConfig).map(
        ([surface, defaultValue]) => [surface, String(defaultValue)],
      ),
    ),
    "",
  ];
}

function metadataReferenceSection(): string[] {
  return [
    "## Semantic Metadata Profiles",
    "",
    "Source: `src/lib/semantic-profile-kinds.ts`.",
    "",
    table(
      ["Profile kind", "Enabled for this site"],
      semanticProfileKinds.map((kind) => [
        kind,
        String(siteConfig.metadata.semanticProfiles.enabled.includes(kind)),
      ]),
    ),
    "",
  ];
}

function mediaReferenceSection(): string[] {
  return [
    "## Media And PDF Policy Vocabulary",
    "",
    "Source: `src/lib/media-policy.ts`.",
    "",
    "### Media Roles",
    "",
    table(["Role"], mediaRoleRows(mediaRoles)),
    "",
    "### Media Surfaces",
    "",
    table(["Surface"], mediaSurfaceRows(mediaSurfaces)),
    "",
    "### Social Preview Policy",
    "",
    table(
      ["Field", "Value"],
      Object.entries(socialPreviewMediaPolicy).map(([key, value]) => [
        key,
        String(value),
      ]),
    ),
    "",
    "### MDX PDF Compatibility Imports",
    "",
    table(
      ["Import", "Mode", "Note"],
      articleMdxPdfCompatibilityPolicies.map((policy) => [
        policy.importSource,
        policy.mode,
        policy.note,
      ]),
    ),
    "",
  ];
}

function mediaRoleRows(roles: readonly MediaRole[]): string[][] {
  return roles.map((role) => [role]);
}

function mediaSurfaceRows(surfaces: readonly MediaSurface[]): string[][] {
  return surfaces.map((surface) => [surface]);
}

function authorDiagnosticReferenceSection(): string[] {
  return [
    "## Author Diagnostic Vocabulary",
    "",
    "Source: `src/lib/author-diagnostics.ts`.",
    "",
    "### Categories",
    "",
    table(
      ["Category"],
      authorDiagnosticCategories.map((category) => [category]),
    ),
    "",
    "### Repair Owners",
    "",
    table(
      ["Repair owner"],
      authorDiagnosticRepairOwners.map((owner) => [owner]),
    ),
    "",
    "### Fixability",
    "",
    table(
      ["Fixability"],
      authorDiagnosticFixabilities.map((fixability) => [fixability]),
    ),
    "",
    "### Diagnostic Sources",
    "",
    table(
      ["Source"],
      authorDiagnosticSources.map((source) => [source]),
    ),
    "",
  ];
}

function sourceArtifactReferenceSection(): string[] {
  const manifest = sourceArtifactManifest(siteInstance, {
    config: siteConfig,
  });

  return [
    "## Source And Generated Artifact Manifest",
    "",
    "Source: `src/lib/source-artifacts.ts`.",
    "",
    table(
      ["Key", "Owner", "Kind", "Role", "Required", "Path"],
      manifest.entries.map((entry) => [
        entry.key,
        entry.owner,
        entry.kind,
        entry.role,
        String(entry.required),
        entry.relativePath,
      ]),
    ),
    "",
  ];
}

function qaCommandReferenceSection(): string[] {
  const commandRows = qaCommandGroups.flatMap((group) =>
    group.scripts.map((script) => [
      script,
      group.domain,
      group.class,
      group.runtime,
      group.mutation,
      group.ciUsage,
    ]),
  );

  return [
    "## QA Commands And Domains",
    "",
    "Source: `package.json` and `scripts/quality/qa-command-registry.ts`.",
    "",
    "### Commands",
    "",
    table(
      ["Script", "Domain", "Class", "Runtime", "Mutation", "CI"],
      commandRows.sort(compareFirstColumn),
    ),
    "",
    "### Domain Coverage",
    "",
    table(
      ["Domain", "Focused scripts", "Release scripts", "CI jobs", "Purpose"],
      qaDomainCoverageRegistry.map((entry) => [
        entry.domain,
        entry.focusedScripts.join(", "),
        entry.releaseScripts.join(", "),
        entry.ciJobs.join(", "),
        entry.purpose,
      ]),
    ),
    "",
  ];
}

function schemaFields(schema: unknown): JsonSchemaField[] {
  return collectSchemaFields(recordValue(schema), "").sort((left, right) =>
    left.path.localeCompare(right.path),
  );
}

function collectSchemaFields(
  schema: JsonRecord,
  prefix: string,
): JsonSchemaField[] {
  const properties = recordValue(schema["properties"]);
  const required = new Set(arrayValue(schema["required"]).filter(isString));
  const fields: JsonSchemaField[] = [];

  for (const [key, value] of Object.entries(properties)) {
    const fieldSchema = recordValue(value);
    const fieldPath = prefix === "" ? key : `${prefix}.${key}`;
    fields.push({
      defaultValue: defaultValueLabel(fieldSchema),
      path: fieldPath,
      required: required.has(key) ? "yes" : "no",
      type: schemaTypeLabel(fieldSchema),
    });
    fields.push(...collectSchemaFields(fieldSchema, fieldPath));
  }

  return fields;
}

function schemaTypeLabel(schema: JsonRecord): string {
  const enumValues = arrayValue(schema["enum"]);
  if (enumValues.length > 0) {
    return `enum: ${enumValues.map(String).join(", ")}`;
  }

  const type = schema["type"];
  if (typeof type === "string") {
    return type;
  }

  if (Array.isArray(type)) {
    return type.filter(isString).join(" | ");
  }

  const anyOf = arrayValue(schema["anyOf"]).map(recordValue);
  if (anyOf.length > 0) {
    return anyOf.map(schemaTypeLabel).join(" | ");
  }

  const oneOf = arrayValue(schema["oneOf"]).map(recordValue);
  if (oneOf.length > 0) {
    return oneOf.map(schemaTypeLabel).join(" | ");
  }

  return "$ref" in schema ? "reference" : "unknown";
}

function defaultValueLabel(schema: JsonRecord): string {
  return "default" in schema ? JSON.stringify(schema["default"]) : "";
}

function compareFirstColumn(
  left: readonly string[],
  right: readonly string[],
): number {
  return (left[0] ?? "").localeCompare(right[0] ?? "");
}

function table(headers: readonly string[], rows: readonly string[][]): string {
  const header = `| ${headers.map(escapeTableCell).join(" | ")} |`;
  const separator = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.map(escapeTableCell).join(" | ")} |`);

  return [header, separator, ...body].join("\n");
}

function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function imageSchemaContext(): { image: () => z.ZodType<ImageMetadata> } {
  return {
    image: () =>
      z
        .string()
        .min(1)
        .transform(
          (source): ImageMetadata => ({
            format: "jpg",
            height: 0,
            src: source,
            width: 0,
          }),
        ),
  };
}

function recordValue(value: unknown): JsonRecord {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return {};
  }

  return Object.fromEntries(Object.entries(value));
}

function arrayValue(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

function outputPathFromArgs(args: readonly string[]): string {
  const outputIndex = args.indexOf("--output");

  if (outputIndex === -1) {
    return defaultOutputPath;
  }

  const outputValue = args[outputIndex + 1];

  if (outputValue === undefined || outputValue.startsWith("--")) {
    throw new Error("Missing value for --output.");
  }

  return path.resolve(outputValue);
}

function usage(): string {
  return [
    "Usage: bun scripts/docs/generate-platform-references.ts [--check] [--quiet] [--output <path>]",
    "",
    "Generates Markdown references from platform schemas and registries.",
    "",
  ].join("\n");
}

if (import.meta.main) {
  process.exitCode = await runGeneratePlatformReferencesCli();
}
