import path from "node:path";

import type { CollectionEntry } from "astro:content";

import { siteConfig, type SiteRouteKey } from "../site/site-config";
import { siteInstance } from "../site/site-instance";

/** Astro content collection entry for a published or draft article. */
export type ArticleEntry = CollectionEntry<"articles">;

/** Astro content collection entry for a published or draft announcement. */
export type AnnouncementEntry = CollectionEntry<"announcements">;

/** Astro content collection entry for author metadata. */
export type AuthorEntry = CollectionEntry<"authors">;

/** Astro content collection entry for category metadata. */
export type CategoryEntry = CollectionEntry<"categories">;

/** Astro content collection entry for editor-owned collections. */
export type EditorialCollectionEntry = CollectionEntry<"collections">;

/** Astro content collection entry for standalone Markdown pages. */
export type PageEntry = CollectionEntry<"pages">;

/** Display-ready category data with its sorted articles. */
export interface CategorySummary {
  articles: ArticleEntry[];
  description?: string | undefined;
  order: number;
  slug: string;
  title: string;
}

export const SITE_TITLE = siteConfig.identity.title;
export const SITE_DESCRIPTION = siteConfig.identity.description;
export const SITE_URL = siteConfig.identity.url;
const RESERVED_ARTICLE_SLUGS = new Set(["all"]);

/**
 * Builds the public announcements index URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function announcementsIndexUrl(): string {
  return withTrailingSlash(siteRoute("announcements"));
}

/**
 * Reads the stable URL slug for an announcement.
 *
 * @param entry Announcement content entry.
 * @returns Announcement slug generated by Astro's content collection ID.
 */
function announcementSlug(entry: AnnouncementEntry): string {
  return entry.id;
}

/**
 * Builds the canonical site URL path for an announcement slug.
 *
 * @param slug Announcement slug generated from the content entry ID.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function announcementUrl(slug: string): string {
  return withTrailingSlash(`${announcementsIndexUrl()}${slug}`);
}

/**
 * Fails fast when multiple announcement entries resolve to the same public slug.
 *
 * @param entries Announcement entries to validate.
 */
export function assertUniqueAnnouncementSlugs(
  entries: AnnouncementEntry[],
): void {
  const seen = new Map<string, string>();

  for (const entry of entries) {
    const slug = announcementSlug(entry);
    const previous = seen.get(slug);

    if (previous !== undefined) {
      throw new Error(
        `Duplicate announcement slug "${slug}" for "${previous}" and "${entry.id}".`,
      );
    }

    seen.set(slug, entry.id);
  }
}

/**
 * Builds the public articles hub URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function articlesIndexUrl(): string {
  return withTrailingSlash(siteRoute("articles"));
}

/**
 * Builds the public URL for the flat all-articles archive.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function articlesArchiveUrl(): string {
  return withTrailingSlash(siteRoute("allArticles"));
}

/**
 * Builds the public authors index URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function authorsIndexUrl(): string {
  return withTrailingSlash(siteRoute("authors"));
}

/**
 * Builds the canonical site URL path for an author profile.
 *
 * @param slug Stable author content entry ID.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function authorUrl(slug: string): string {
  return withTrailingSlash(`${authorsIndexUrl()}${slug}`);
}

/**
 * Builds the public global bibliography URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function bibliographyUrl(): string {
  return withTrailingSlash(siteRoute("bibliography"));
}

/**
 * Reads the stable URL slug for an article.
 *
 * @param entry Article content entry.
 * @returns Article slug generated by Astro's content collection ID.
 */
export function articleSlug(entry: ArticleEntry): string {
  return entry.id;
}

/**
 * Builds the canonical site URL path for an article slug.
 *
 * @param slug Article slug generated from the content entry ID.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function articleUrl(slug: string): string {
  return withTrailingSlash(`${articlesIndexUrl()}${slug}`);
}

/**
 * Fails fast when multiple article entries resolve to the same public slug.
 *
 * @param entries Article entries to validate.
 */
export function assertUniqueArticleSlugs(entries: ArticleEntry[]): void {
  const seen = new Map<string, string>();

  for (const entry of entries) {
    const slug = articleSlug(entry);
    const previous = seen.get(slug);

    if (previous !== undefined) {
      throw new Error(
        `Duplicate article slug "${slug}" for "${previous}" and "${entry.id}".`,
      );
    }

    if (RESERVED_ARTICLE_SLUGS.has(slug)) {
      throw new Error(`Article slug "${slug}" is reserved for a site route.`);
    }

    seen.set(slug, entry.id);
  }
}

/**
 * Reads the display author for an article.
 *
 * @param entry Article content entry.
 * @returns Author display name.
 */
export function authorName(entry: ArticleEntry): string {
  return entry.data.author;
}

/**
 * Reads the category slug from an article's source path.
 *
 * @param entry Article content entry.
 * @returns Category folder slug, or an empty string when no category is found.
 */
export function categorySlug(entry: ArticleEntry): string {
  const relativePath = articleFileRelativePath(entry.filePath ?? "");

  return relativePath.includes("/") ? (relativePath.split("/")[0] ?? "") : "";
}

function articleFileRelativePath(filePath: string): string {
  if (filePath.length === 0) {
    return "";
  }

  const normalizedFilePath = normalizeFilesystemPath(filePath);
  const articleRoot = normalizeFilesystemPath(siteInstance.content.articles);
  const rootPrefix = articleRoot.endsWith("/")
    ? articleRoot
    : `${articleRoot}/`;

  if (normalizedFilePath.startsWith(rootPrefix)) {
    return normalizedFilePath.slice(rootPrefix.length);
  }

  const projectRelativeArticleRoot = normalizeFilesystemPath(
    path.relative(process.cwd(), siteInstance.content.articles),
  );
  const knownRootMarkers = [
    `/${projectRelativeArticleRoot}/`,
    `${projectRelativeArticleRoot}/`,
    "/site/content/articles/",
    "site/content/articles/",
    "/src/content/articles/",
    "src/content/articles/",
  ];
  const marker = knownRootMarkers.find((candidate) =>
    normalizedFilePath.includes(candidate),
  );

  return marker === undefined
    ? normalizedFilePath
    : (normalizedFilePath.split(marker)[1] ?? "");
}

function normalizeFilesystemPath(filePath: string): string {
  return filePath.replaceAll(path.sep, "/");
}

/**
 * Builds the public category archive URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function categoriesIndexUrl(): string {
  return withTrailingSlash(siteRoute("categories"));
}

/**
 * Builds the canonical site URL path for a category slug.
 *
 * @param slug Category slug.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function categoryUrl(slug: string): string {
  return withTrailingSlash(`${categoriesIndexUrl()}${slug}`);
}

/**
 * Builds the public editorial collections index URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function collectionsIndexUrl(): string {
  return withTrailingSlash(siteRoute("collections"));
}

/**
 * Builds the canonical site URL path for an editorial collection.
 *
 * @param slug Stable collection content entry ID.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function collectionUrl(slug: string): string {
  return withTrailingSlash(`${collectionsIndexUrl()}${slug}`);
}

/**
 * Decodes the small set of HTML entities still present in legacy frontmatter.
 *
 * @param value Text that may include numeric or common named HTML entities.
 * @returns Text with supported entities decoded.
 */
export function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&#(\d+);/g, (_, codePoint: string) =>
      String.fromCodePoint(Number(codePoint)),
    )
    .replace(/&#x([0-9a-f]+);/gi, (_, codePoint: string) =>
      String.fromCodePoint(Number.parseInt(codePoint, 16)),
    )
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

/**
 * Reads the publication date for an article.
 *
 * @param entry Article content entry.
 * @returns Article publication date.
 */
export function entryDate(entry: ArticleEntry): Date {
  return entry.data.date;
}

/**
 * Reads an article title as user-facing text.
 *
 * @param entry Article content entry.
 * @returns Decoded article title.
 */
export function entryTitle(entry: ArticleEntry): string {
  return decodeHtmlEntities(entry.data.title);
}

/**
 * Reads the article description used in cards, feeds, and metadata.
 *
 * @param entry Article content entry.
 * @returns Article description.
 */
export function excerpt(entry: ArticleEntry): string {
  return entry.data.description;
}

/**
 * Builds the public RSS feed URL.
 *
 * @returns Absolute-path URL for the RSS endpoint.
 */
export function feedUrl(): string {
  return siteRoute("feed");
}

/**
 * Formats a date for reader-facing article metadata.
 *
 * @param date Date to format.
 * @returns Localized date text, or an empty string for missing/invalid dates.
 */
export function formatDate(date: Date | undefined): string {
  if (date === undefined || Number.isNaN(date.getTime())) {
    return "";
  }
  return new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date);
}

/**
 * Reads the resolved image URL for an article image field.
 *
 * @param entry Article content entry.
 * @returns Image URL when the article has an image.
 */
export function imageUrl(entry: ArticleEntry): string | undefined {
  return imageSource(entry.data.image);
}

/**
 * Checks whether an article should be included in public site surfaces.
 *
 * @param entry Article content entry.
 * @returns True when the article is not marked as a draft.
 */
export function isPublishedArticle(entry: ArticleEntry): boolean {
  return !entry.data.draft;
}

/**
 * Checks whether an announcement should be included in public site surfaces.
 *
 * @param entry Announcement content entry.
 * @returns True when the announcement is not marked as a draft.
 */
export function isPublishedAnnouncement(entry: AnnouncementEntry): boolean {
  return !entry.data.draft;
}

/**
 * Converts free-form text into the URL-safe slug format used by the site.
 *
 * @param value Raw text to normalize.
 * @returns Lowercase dash-separated slug text.
 */
export function normalizeSlug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Builds a stable public URL for a top-level Markdown page.
 *
 * @param slug Page slug without slashes.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function pageUrl(slug: string): string {
  return withTrailingSlash(`/${normalizeSlug(slug)}`);
}

/**
 * Builds the public search page URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function searchUrl(): string {
  return withTrailingSlash(siteRoute("search"));
}

/**
 * Builds the public tag index URL.
 *
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function tagsIndexUrl(): string {
  return withTrailingSlash(siteRoute("tags"));
}

/**
 * Builds the canonical site URL path for a canonical tag label.
 *
 * @param tag Canonical normalized tag label.
 * @returns Absolute-path URL with the encoded tag and configured trailing slash.
 */
export function tagUrl(tag: string): string {
  return withTrailingSlash(`${tagsIndexUrl()}${encodeURIComponent(tag)}`);
}

/**
 * Sorts articles by newest publication date, with slug as a stable tiebreaker.
 *
 * @param entries Article entries to sort.
 * @returns New sorted array without mutating the input.
 */
export function sortNewestFirst(entries: ArticleEntry[]): ArticleEntry[] {
  return Array.from(entries).sort((a, b) => {
    const bTime = entryDate(b).getTime();
    const aTime = entryDate(a).getTime();
    const dateSort = bTime - aTime;
    return dateSort !== 0
      ? dateSort
      : articleSlug(a).localeCompare(articleSlug(b));
  });
}

/**
 * Sorts announcements by newest publication date, with slug as a stable tiebreaker.
 *
 * @param entries Announcement entries to sort.
 * @returns New sorted array without mutating the input.
 */
export function sortAnnouncementsNewestFirst(
  entries: AnnouncementEntry[],
): AnnouncementEntry[] {
  return Array.from(entries).sort((a, b) => {
    const dateSort = b.data.date.getTime() - a.data.date.getTime();
    return dateSort !== 0
      ? dateSort
      : announcementSlug(a).localeCompare(announcementSlug(b));
  });
}

function imageSource(value: unknown): string | undefined {
  if (
    typeof value === "object" &&
    value !== null &&
    "src" in value &&
    typeof value.src === "string"
  ) {
    return value.src;
  }

  return undefined;
}

function siteRoute(key: SiteRouteKey): string {
  switch (key) {
    case "allArticles": {
      return siteConfig.routes.allArticles;
    }
    case "announcements": {
      return siteConfig.routes.announcements;
    }
    case "articles": {
      return siteConfig.routes.articles;
    }
    case "authors": {
      return siteConfig.routes.authors;
    }
    case "bibliography": {
      return siteConfig.routes.bibliography;
    }
    case "categories": {
      return siteConfig.routes.categories;
    }
    case "collections": {
      return siteConfig.routes.collections;
    }
    case "feed": {
      return siteConfig.routes.feed;
    }
    case "home": {
      return siteConfig.routes.home;
    }
    case "search": {
      return siteConfig.routes.search;
    }
    case "tags": {
      return siteConfig.routes.tags;
    }
  }
}

function withTrailingSlash(path: string): string {
  if (path === "") {
    return "/";
  }
  return path.endsWith("/") ? path : `${path}/`;
}
