[package]
name = "tpm-studio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
name = "tpm_studio"
path = "src/lib.rs"

[[bin]]
name = "tpm-studio"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = [] }
tpm-operations.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
